



# variables
PRIX_ESSENCE = 2
DAYWEEK = 4
# TODO epsilon est la variable qui permet d'assurer que les routes ne sont pas trop longue. une route ne doit pas exceder EPSILON+TIMEBOAT 
EPSILON = 0.1
TIMEBOAT = 14
TIMEBOATNT = 10
TIMEESCALE = 6
TIMEBOATCAMPAGNE = 20
TIMEBOATLONG = 38
MAXLONGROUTE = 5
TIMEBOATAFFPORT = 16
ROADPERMONTH = 3
MINDAYMOVE = 8
NBJOURS = 208
SEASON = 52


# Liste des ports dans l'ordre pour chaque zone
ORDEREDMED = [["SETE","MARSEILLE","TOULON","CANNES"],["ILE ROUSSE","AJACCIO","BONIFACIO","BASTIA"]]
ORDEREDATL = [["DUNKERQUE","CALAIS","BOULOGNE","ST VALERY SUR SOMME","DIEPPE","FECAMP","LE HAVRE","OUISTREHAM","BESSIN","CHERBOURG","GRANVILLE","SAINT-MALO","LEZARDRIEUX","MORLAIX","ROSCOFF","ABERWRACH","PORTSALL","OUESSANT","BREST","DOUARNENEY","ILE DE SEIN","LE GUILVINEC","CONCARNEAU","LORIENT","BELLE ILE","ST NAZAIRE","NOIRMOUTIER","LES SABLES D'OLONNE","LA ROCHELLE","LE VERDON","PAUPILLAC","ARCACHON","BAYONNE","LOCTUDY"]]


# Tableau des rewards pour chaque balise.
REWARD = [[1,0,0],[1,8,0],[1,6,40]]
# REWARD[bat.type-1][int.type-1]


BASETECHNIQUENAVIREATL = {"DUNKERQUE" : True, "CALAIS" : True, "BOULOGNE" : True, "ST VALERY SUR SOMME" : True, "DIEPPE" : False, "FECAMP" : False, "LE HAVRE" : True, "OUISTREHAM" : True, "BESSIN" : False, "CHERBOURG" : True, "GRANVILLE" : True, "SAINT-MALO" : True, "LEZARDRIEUX" : True, "MORLAIX" : True, "ROSCOFF" : False, "ABERWRACH" : False, "PORTSALL" : False, "OUESSANT" : False, "BREST" : True, "DOUARNENEY" : False, "ILE DE SEIN" : False, "LE GUILVINEC" : False, "CONCARNEAU" : True, "LORIENT" : True, "BELLE ILE" : False, "ST NAZAIRE" : True, "NOIRMOUTIER" : True, "LES SABLES D'OLONNE" : True, "LA ROCHELLE" : True, "LE VERDON" : True, "PAUPILLAC" : False, "ARCACHON" : True, "BAYONNE" : True, "LOCTUDY" : False}
BASETECHNIQUENAVIREMED = {"SETE" : True, "MARSEILLE" : True, "TOULON" : True, "CANNES" : True, "ILE ROUSSE" : False, "AJACCIO" : True, "BONIFACIO" : True, "BASTIA" : True}

